name: "(Release) Release dev container templates"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      
      - uses: actions/checkout@v3

      - name: Publish template
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.NEFARIOUS_TOKEN }}
        
  release:
    name: Generate release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      contents: write
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate version and release
        env:
          GITHUB_TOKEN: ${{ secrets.NEFARIOUS_TOKEN }}
        run: npm run semantic-release